version: '3'
services:
  server:
    build: ./server
    depends_on:
      - mysql
      - redis
    ports:
    - "3000:3000"
    volumes:
    - ./serverLog:/go/serverLog
  webapp:
    build: ./webapp
    ports:
    - "80:80"
    - "443:443"
    volumes:
    - ./nginx:/etc/nginx/conf.d
    depends_on:
      - server
  redis:
    image: "redis:alpine"
    ports:
    - "6379:6379"
    restart: on-failure
  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
    - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ./server/test/:/docker-entrypoint-initdb.d/
  adminer:
    image: adminer
    restart: on-failure
    depends_on:
      - mysql
    ports:
      - "8080:8080"


volumes:
  mysql-data: {}
  server-log: {}